### ISSUE TITLE
Could you please add the initial longitude setting?

### ISSUE THREAD

**Issue by airzope** [hellpig/trajectory-thingy#1]
I found that I cannot set the initial longitude, only the altitude and latitude can be set.The default longitude is 0.

**Comment by hellpig** [comment]
On a spherical Earth, only the *change* in the longitude makes any physical difference. The longitude set in the code is relative to a start longitude of 0, so you can think of it as the *change* in the longitude.

**Comment by airzope** [comment]
Thank you for your patience, I understand after your explanation.

**Comment by airzope** [comment]
https://en.wikipedia.org/wiki/Earth_radius 
A globally-average value is usually considered to be 6,371 kilometres

#define re 6.27e6          // average radius of Earth

**Comment by airzope** [comment]
If I didn't launch from zero latitude, the distance calculation would be incorrect.

**Comment by airzope** [comment]
When I output the velocity, I find that the initial velocity seems too large, which is much higher than the first cosmic speed of 7.9km/s

**Comment by hellpig** [comment]
6.27e6 has been changed to 6.37e6
Thanks!

th0 now used in great-circle-distance calculation (instead of lat0) because lat0 was in degrees instead of radians
Thanks!

Velocities may be large due to having to punch through the atmosphere. Consider setting alt0 to above the atmosphere.
